server:
  port: 8080
spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      mvc:
        routes:
        - id: student-ms
          uri: lb://STUDENT-MS
          predicates:
            - Path=/student/**

        - id: grade-ms
          uri: lb://GRADE-MS
          predicates:
            - Path=/grade/**
    loadbalancer:
      ribbon:
        enabled: 'false'

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}